name: CI

on: 
 push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: pip install pytest
      - run: pip install pylint

      - name: Run tests
        run:  pytest 
        

      - name: report making
        run: pylint calculator.py || true
