name: Nginx Docker CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Image
        run: docker build -t my-nginx-demo .

      - name: Start Container
        run: docker run -d -p 8080:80 --name website my-nginx-demo


  logs:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Image Again
        run: docker build -t my-nginx-demo .

      - name: Show Containers
        run: docker ps -a

      - name: Show Logs
        run: docker logs website

  deploy:
    needs: logs
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Curl Test
        run: curl http://localhost:8080